apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      database: web
  template:
    metadata:
      labels:
        database: web
    spec:
      containers:
      - name: database-site
        image: rattrapagecloud/host:04
---
apiVersion: v1
kind: Service
metadata:
  name: database-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    database: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30003
---
apiVersion: v1
kind: Service
metadata:
  name: database-balancer
  namespace: default
spec:
  type: LoadBalancer
  selector:
    database: web
  ports:
  - port: 8080
    targetPort: 8080


