apiVersion: app/v1
kind: Deployment
metadata:
  name: host
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      host: web
  template:
    metadata:
      labels:
        host: web
    spec:
      containers:
      - name: host-site
        image: host:01
---
apiVersion: v1
kind: Service
metadata:
  name: host-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    host: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001


