apiVersion: apps/v1
kind: Deployment
metadata:
  name: host
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      host: web
  template:
    metadata:
      labels:
        host: web
    spec:
      containers:
      - name: host-site
        image: rattrapagecloud/host:04
---
apiVersion: v1
kind: Service
metadata:
  name: host-balancer
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: host
  ports:
  - port: 8080
    targetPort: 8080
