apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      login: web
  template:
    metadata:
      labels:
        login: web
    spec:
      containers:
      - name: login-site
        image: rattrapagecloud/host:04
---
apiVersion: v1
kind: Service
metadata:
  name: login-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    login: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: login-balancer
  namespace: default
spec:
  type: LoadBalancer
  selector:
    login: web
  ports:
  - port: 8080
    targetPort: 8080


